-- V1 — Baseline schema.
--
-- This file is not a design. It is a transcription.
--
-- Up to Chapter 22 the schema was whatever Hibernate emitted from the entities under
-- `ddl-auto: create-drop`, and it existed only for as long as the application was running. To
-- write this migration the application was started once against cartwise_dev, the schema it built
-- was exported with
--
--     pg_dump -U cartwise -h localhost -d cartwise_dev --schema-only --no-owner --no-privileges
--
-- and that output was cleaned (dump header, SET statements, search_path pinning, per-object
-- comment banners removed) and reordered into dependency order. Nothing here was recalled from
-- the entity classes. That distinction is the point of the exercise: the baseline has to reproduce
-- the schema that actually existed, including the parts nobody chose on purpose, because from the
-- next boot onward `ddl-auto: validate` compares the entities against THIS file's output and any
-- difference is a startup failure.
--
-- Consequences of that, visible below and deliberately not tidied:
--
--   * Column order is Hibernate's, not a human's. It groups by type width — booleans and numerics,
--     then timestamps and bigints, then varchars in ascending length — which is why `products`
--     reads as `in_stock, original_price, price, rating, review_count, created_at, id, updated_at,
--     category, brand, slug, name, image_url` instead of anything a person would write. Column
--     order is not semantically meaningful in PostgreSQL, and re-sorting it here would make the
--     next `pg_dump` diff against this file noisy for no gain.
--
--   * `"position"` is quoted in `comparisons`. It is a reserved word in SQL, and Hibernate quotes
--     it. Unquoting it would work in PostgreSQL and would be a gratuitous divergence.
--
--   * `users_role_check` and `products_pkey`-style names are PostgreSQL's and Hibernate's defaults
--     rather than chosen names. They are reproduced verbatim so that a constraint violation message
--     from a migrated database is the same string as one from the old create-drop database — the
--     error text is in this project's tests and docs already.
--
-- Table names are plural: products, users, wishlists, comparisons. Every @Table in
-- com.cartwise.entity names them that way.
--
-- Tables are created parents-first (products, users) then children (wishlists, comparisons) so the
-- foreign keys can be declared inline instead of bolted on by a trailing ALTER TABLE block the way
-- pg_dump writes them. That is the one structural liberty taken with the export, and it is
-- behaviour-preserving: the resulting constraints have the same names, columns and referents.


-- ---------------------------------------------------------------------------------------------
-- products — the catalogue. Chapter 16.
-- ---------------------------------------------------------------------------------------------
--
-- `numeric(12,2)` for money, not double precision: prices are rupees and exact, and a binary
-- floating point type cannot represent 129999.00 exactly. `numeric(2,1)` for rating is the one
-- decimal place the frontend renders — the column cannot hold a value the UI would have to round.
--
-- original_price is the only nullable numeric here, and its nullability is load-bearing: NULL means
-- "not discounted", which is a different statement from a discount of zero.
CREATE TABLE products (
    in_stock       boolean                     NOT NULL,
    original_price numeric(12, 2),
    price          numeric(12, 2)              NOT NULL,
    rating         numeric(2, 1)               NOT NULL,
    review_count   integer                     NOT NULL,
    created_at     timestamp(6) with time zone NOT NULL,
    id             bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at     timestamp(6) with time zone NOT NULL,
    category       character varying(60)       NOT NULL,
    brand          character varying(80)       NOT NULL,
    slug           character varying(120)      NOT NULL,
    name           character varying(200)      NOT NULL,
    image_url      character varying(500),
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_slug_key UNIQUE (slug)
);

-- Declared on the entity as @Index. See the class comment on com.cartwise.entity.Product for what
-- each one serves and, more usefully, what they do NOT serve: neither can satisfy the ?category=
-- filter, which compares lower(category). V2 adds the index that can.
CREATE INDEX idx_products_category ON products USING btree (category);
CREATE INDEX idx_products_price ON products USING btree (price);


-- ---------------------------------------------------------------------------------------------
-- users — accounts. Chapter 17, credentialed in Chapter 18, given a role in Chapter 19.
-- ---------------------------------------------------------------------------------------------
--
-- password_hash is varchar(100) holding a 60-character BCrypt output; the headroom is for a future
-- encoder with a longer format, not padding. It is NOT NULL because an account without a
-- credential is not a state this application has a meaning for.
--
-- users_role_check is generated by Hibernate from @Enumerated(EnumType.STRING) on the Role enum.
-- It is reproduced rather than dropped, and that has a maintenance consequence worth stating
-- plainly: adding a value to com.cartwise.entity.Role now requires a migration that rewrites this
-- constraint, or every insert of the new role fails. Hibernate used to regenerate it silently on
-- every boot. Making that visible is the trade this chapter is making.
CREATE TABLE users (
    created_at    timestamp(6) with time zone NOT NULL,
    id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL,
    role          character varying(20)       NOT NULL,
    password_hash character varying(100)      NOT NULL,
    email         character varying(254)      NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    -- Written as Hibernate writes it — `check ((role in ('USER','ADMIN')))` — and NOT as pg_dump
    -- prints it back. The two are not interchangeable at the character level, which is worth the
    -- three lines it takes to explain because it is the only place the export needed correcting.
    --
    -- pg_dump deparses this constraint as
    --     CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, ...])::text[])))
    -- and pasting THAT into a migration produces a constraint PostgreSQL stores as
    --     CHECK (((role)::text = ANY (ARRAY[('USER'::character varying)::text, ...])))
    -- — the cast moves inside the array. Same meaning, same accepted values, different stored
    -- expression, and therefore a permanent one-line difference between a schema built by
    -- Hibernate and a schema built by this file. Round-tripping a deparsed expression back through
    -- the parser is simply not guaranteed to land on the same tree. Feeding PostgreSQL the same
    -- input Hibernate fed it does land on the same tree, and a `pg_dump | diff` of the two schemas
    -- is now empty apart from V2's index. Verified both ways rather than assumed.
    CONSTRAINT users_role_check CHECK ((role IN ('USER', 'ADMIN')))
);


-- ---------------------------------------------------------------------------------------------
-- wishlists — saved products, per user. Chapter 17.
-- ---------------------------------------------------------------------------------------------
--
-- uk_wishlist_user_product is the database's own version of "you cannot save the same product
-- twice". The service checks it too; this constraint is what makes the check true under concurrent
-- requests, where two simultaneous POSTs both read "not present" before either writes.
CREATE TABLE wishlists (
    created_at timestamp(6) with time zone NOT NULL,
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id bigint                      NOT NULL,
    user_id    bigint                      NOT NULL,
    CONSTRAINT wishlists_pkey PRIMARY KEY (id),
    CONSTRAINT uk_wishlist_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_wishlist_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id) REFERENCES products (id)
);


-- ---------------------------------------------------------------------------------------------
-- comparisons — up to four products per user, in fixed slots. Chapter 17.
-- ---------------------------------------------------------------------------------------------
--
-- Three constraints encode the whole rule set, and none of them is redundant with the others:
--   ck_comparison_position_range  — a slot is 0..3, so "at most four" is structural rather than a
--                                   count the service has to remember to enforce.
--   uk_comparison_user_position   — one product per slot.
--   uk_comparison_user_product    — the same product cannot occupy two slots. This is the one the
--                                   API's "duplicate" response is built on.
CREATE TABLE comparisons (
    "position" integer                     NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id bigint                      NOT NULL,
    user_id    bigint                      NOT NULL,
    CONSTRAINT comparisons_pkey PRIMARY KEY (id),
    CONSTRAINT uk_comparison_user_position UNIQUE (user_id, "position"),
    CONSTRAINT uk_comparison_user_product UNIQUE (user_id, product_id),
    CONSTRAINT ck_comparison_position_range CHECK ((("position" >= 0) AND ("position" <= 3))),
    CONSTRAINT fk_comparison_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_comparison_product FOREIGN KEY (product_id) REFERENCES products (id)
);
