-- V5 — Affiliate click tracking.
--
-- Chapter 26. CartWise earns nothing today: it compares prices and sends people elsewhere to buy.
-- This is the table behind the first revenue model the project has had — an affiliate referral,
-- where a retailer pays a commission for a customer CartWise sent them. The transaction itself
-- happens entirely on the retailer's site. There is no cart here, no checkout, no payment, and this
-- migration deliberately adds nothing that would be a step toward one.
--
-- WHAT A ROW MEANS
--
-- One row is one outbound click: somebody, at some moment, left CartWise for a named retailer via a
-- named product's "Visit store" button. That is the whole record. It is written by the redirect
-- endpoint *before* the 302 goes out, so a click that was tracked is a click that actually left.
--
-- WHAT IS DELIBERATELY NOT STORED, AND WHY
--
-- No IP address. No user agent. No referrer. No request body. No cookie or device identifier. None
-- of the six is needed to answer the questions this table exists to answer — how many people clicked
-- through, to whom, for what, and when — and every one of them would turn an aggregate counter into
-- a behavioural profile of identifiable people. A click-tracking table is exactly the kind of thing
-- that accretes "just one more column" until it is a surveillance log, so the omissions are recorded
-- here rather than left to be noticed later.
--
-- The one identifier stored is user_id, and only when the caller was already authenticated. It is a
-- foreign key to an account that already exists, carrying nothing the users table does not; it is
-- what makes "which of our signed-in users actually convert" answerable at all. An anonymous click
-- stores NULL and stays anonymous — it is NOT backfilled from a session, a cookie or an address.
--
-- NULLABILITY IS THE POINT, NOT AN OVERSIGHT
--
-- user_id is nullable because most clicks genuinely have no user. Substituting a sentinel (0, -1, a
-- "guest" row) would make "we do not know who this was" indistinguishable from "this was a
-- particular account", and the analytics query that splits signed-in from anonymous traffic depends
-- on the difference being representable.


CREATE TABLE affiliate_clicks (
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,

    -- Which product's offer was clicked. NOT NULL: a click with no product is not a click, and
    -- per-product analytics is the whole point of the column.
    --
    -- ON DELETE CASCADE. A product removed from the catalogue takes its click history with it,
    -- because every question this table answers about a product ("how many clicks did the Pixel 10
    -- get") stops having a subject once the product is gone. The alternative — orphan rows naming a
    -- product id nothing resolves — is a report that silently under- or mis-counts.
    product_id bigint                      NOT NULL,

    -- Who clicked, when they were signed in. NULL means anonymous, and that is the common case.
    --
    -- ON DELETE SET NULL, deliberately different from the product rule above. Deleting an account
    -- must not delete the fact that a referral happened — the commission it may have earned is real
    -- whether or not the account still exists — so the click survives and simply becomes anonymous.
    -- That is also the behaviour an erasure request wants: forget the person, keep the count.
    user_id    bigint,

    -- Retailer id as the application knows it: 'amazon', 'flipkart', 'croma', 'reliance-digital',
    -- 'vijay-sales'. Text rather than a foreign key to a retailers table, because there is no
    -- retailers table — the five live in configuration (cartwise.affiliate.retailers), which is what
    -- lets a real affiliate tag be dropped in by environment variable without a schema change. The
    -- cost is that this column can hold a retailer the configuration no longer names; the endpoint
    -- rejects unknown ids at write time, so that can only happen to historic rows, which is the
    -- correct outcome for a report about the past.
    --
    -- 40 characters is generous for the longest id in use ('reliance-digital', 16).
    retailer   character varying(40)       NOT NULL,

    -- When the click happened, from the application clock at the moment the redirect was built.
    -- timestamptz to match every other instant in this schema.
    clicked_at timestamp(6) with time zone NOT NULL,

    CONSTRAINT affiliate_clicks_pkey PRIMARY KEY (id),
    CONSTRAINT fk_affiliate_click_product FOREIGN KEY (product_id)
        REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_affiliate_click_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE SET NULL
);

-- Three indexes, one per aggregate the admin report runs. Unlike the product indexes in V1 — which
-- were added to a table of fifty rows and admitted as much — these cover a table that grows once per
-- outbound click and has no natural ceiling, so they are the difference between a report that stays
-- fast and one that degrades with traffic.
--
-- clicked_at is DESC because every query on it is "recently", never "from the beginning".
CREATE INDEX idx_affiliate_clicks_clicked_at ON affiliate_clicks USING btree (clicked_at DESC);
CREATE INDEX idx_affiliate_clicks_product ON affiliate_clicks USING btree (product_id);
CREATE INDEX idx_affiliate_clicks_retailer ON affiliate_clicks USING btree (retailer);

-- No index on user_id. It is nullable and overwhelmingly NULL, so an index over it would be almost
-- entirely one value — and nothing queries by user: the analytics are aggregate, and "show me one
-- person's click history" is a question this chapter deliberately does not build a way to ask.
